"""empty message

Revision ID: 29c483a72d41
Revises: e1bdf18af104
Create Date: 2021-01-31 20:59:07.622802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29c483a72d41'
down_revision = 'e1bdf18af104'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('phone', table_name='user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('phone', 'user', ['phone'], unique=True)
    # ### end Alembic commands ###
