"""empty message

Revision ID: 6daef38f03c1
Revises: a3a68a89a31a
Create Date: 2021-02-01 17:29:43.463752

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6daef38f03c1'
down_revision = 'a3a68a89a31a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('phone', table_name='request_form')
    op.drop_table('request_form')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('request_form',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('phone', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', mysql.VARCHAR(collation='utf8_unicode_ci', length=140), nullable=True),
    sa.Column('email', mysql.VARCHAR(collation='utf8_unicode_ci', length=140), nullable=True),
    sa.Column('city', mysql.VARCHAR(collation='utf8_unicode_ci', length=140), nullable=True),
    sa.Column('comment', mysql.TEXT(collation='utf8_unicode_ci'), nullable=True),
    sa.Column('id_car', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('phone', 'request_form', ['phone'], unique=True)
    # ### end Alembic commands ###
