"""empty message

Revision ID: 89bbbd8703a3
Revises: 6daef38f03c1
Create Date: 2021-02-01 17:33:24.767639

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '89bbbd8703a3'
down_revision = '6daef38f03c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('request_form',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=12), nullable=True),
    sa.Column('name', sa.String(length=140), nullable=True),
    sa.Column('email', sa.String(length=140), nullable=True),
    sa.Column('city', sa.String(length=140), nullable=True),
    sa.Column('comment', sa.Text(length=140), nullable=True),
    sa.Column('id_car', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.drop_table('avto')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('avto',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8_unicode_ci', length=255), nullable=True),
    sa.Column('price', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('transmission', mysql.VARCHAR(collation='utf8_unicode_ci', length=255), nullable=True),
    sa.Column('drive_unit', mysql.VARCHAR(collation='utf8_unicode_ci', length=255), nullable=True),
    sa.Column('engen', mysql.VARCHAR(collation='utf8_unicode_ci', length=255), nullable=True),
    sa.Column('type_engen', mysql.VARCHAR(collation='utf8_unicode_ci', length=255), nullable=True),
    sa.Column('url', mysql.TEXT(collation='utf8_unicode_ci'), nullable=True),
    sa.Column('year', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=True),
    sa.Column('city', mysql.VARCHAR(collation='utf8_unicode_ci', length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('request_form')
    # ### end Alembic commands ###
