"""empty message

Revision ID: c9b738e4c88d
Revises: 89bbbd8703a3
Create Date: 2021-02-01 17:34:45.828385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9b738e4c88d'
down_revision = '89bbbd8703a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('avto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('price', sa.String(length=100), nullable=True),
    sa.Column('transmission', sa.String(length=255), nullable=True),
    sa.Column('drive_unit', sa.String(length=255), nullable=True),
    sa.Column('engen', sa.String(length=255), nullable=True),
    sa.Column('type_engen', sa.String(length=255), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('year', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('avto')
    # ### end Alembic commands ###
